[[env]]
  # Build settings
  [build]
    command = "npm run build"
    publish = ".next"

  # Redirect rules for Next.js
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  # Environment variables (you'll need to set these in Netlify dashboard)
  # NEXT_PUBLIC_FIREBASE_API_KEY
  # NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
  # NEXT_PUBLIC_FIREBASE_PROJECT_ID
  # NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
  # NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
  # NEXT_PUBLIC_FIREBASE_APP_ID
  # NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
  # EMAIL_USER
  # EMAIL_APP_PASSWORD
  # RECIPIENT_EMAIL
